import { Quiz } from "../../../../types";

export const basicOperatingSystem: Quiz = {
  id: "01-operating-system-01",
  title: "Basic Operating System 01",
  description: "Basic Operating System MCQs",
  timeLimit: 3000,
  questions: [
  {
    "question": "Which of the following is the main function of the Operating System?",
    "options": ["Document authoring", "Resource Management", "Designing hardware", "Internet browsing"],
    "answer": 1
  },
  {
    "question": "The process of loading the operating system into memory is called:",
    "options": ["Starting", "Processing", "Booting", "Logging"],
    "answer": 2
  },
  {
    "question": "In an operating system, what is a \"Process\"?",
    "options": ["A high-level programming language", "A program in execution", "A set of instructions in a file", "A hardware component"],
    "answer": 1
  },
  {
    "question": "Which state does a process enter if it is waiting for an I/O operation?",
    "options": ["Running state", "Ready state", "Blocked/Waiting state", "Terminated state"],
    "answer": 2
  },
  {
    "question": "A situation where two or more processes are waiting indefinitely for an event that can be caused only by one of the waiting processes is known as:",
    "options": ["Starvation", "Deadlock", "Context Switching", "Thrashing"],
    "answer": 1
  },
  {
    "question": "The strategy of allowing a process that is \"ready\" to take over the CPU while another process is currently running is called:",
    "options": ["Non-preemptive scheduling", "Preemptive scheduling", "First-Come, First-Served", "Batch processing"],
    "answer": 1
  },
  {
    "question": "The PCB (Process Control Block) does NOT contain which of the following?",
    "options": ["Process state", "Program counter", "Bootstrap loader code", "CPU registers"],
    "answer": 2
  },
  {
    "question": "Which scheduling algorithm is designed specifically for time-sharing systems?",
    "options": ["FCFS (First-Come, First-Served)", "SJF (Shortest Job First)", "Round Robin", "Priority Scheduling"],
    "answer": 2
  },
  {
    "question": "What is \"Context Switching\"?",
    "options": ["Switching from one user account to another", "Switching the CPU from one process to another", "Installing a new operating system", "Changing the background wallpaper"],
    "answer": 1
  },
  {
    "question": "The interval from the time of submission of a process to the time of completion is known as:",
    "options": ["Waiting time", "Response time", "Turnaround time", "Throughput"],
    "answer": 2
  },
  {
    "question": "The technique that allows the execution of processes that are not completely in memory is:",
    "options": ["Swapping", "Virtual Memory", "Caching", "Fragmentation"],
    "answer": 1
  },
  {
    "question": "In memory management, \"Paging\" helps to avoid which of the following?",
    "options": ["Internal fragmentation", "External fragmentation", "Deadlock", "Paging errors"],
    "answer": 1
  },
  {
    "question": "A \"Page Fault\" occurs when:",
    "options": ["The page is found in memory", "The page is not found in memory (it must be fetched from disk)", "The CPU crashes", "The memory is too fast"],
    "answer": 1
  },
  {
    "question": "Which of the following are common replacement policies for pages in memory?",
    "options": ["FIFO, LRU, Optimal", "TCP, IP, UDP", "FCFS, SJF, Round Robin", "NTFS, FAT32, EXT4"],
    "answer": 0
  },
  {
    "question": "The Logical Address is generated by the:",
    "options": ["Hard drive", "RAM", "CPU", "Operating System"],
    "answer": 2
  },
  {
    "question": "The mapping of a logical address to a physical address is done by which hardware component?",
    "options": ["ALU", "Memory Management Unit (MMU)", "Control Unit", "DMA Controller"],
    "answer": 1
  },
  {
    "question": "Which fragmentation occurs when unused memory is internal to a specific partition?",
    "options": ["External fragmentation", "Virtual fragmentation", "Internal fragmentation", "Segment fragmentation"],
    "answer": 2
  },
  {
    "question": "\"Belady's Anomaly\" (where adding more page frames leads to more page faults) is related to which algorithm?",
    "options": ["LRU", "Optimal", "FIFO", "LIFO"],
    "answer": 2
  },
  {
    "question": "What is a \"Segment Table\"?",
    "options": ["A table that lists all files on a drive", "A table that contains the base address and limit of segments", "A table used for IP routing", "A list of user passwords"],
    "answer": 1
  },
  {
    "question": "\"Thrashing\" occurs when:",
    "options": ["The CPU is idle", "The system spends more time paging (swapping) than executing", "The hard drive is full", "Multiple users log in at once"],
    "answer": 1
  },
  {
    "question": "What is the \"Kernel\"?",
    "options": ["The user interface of an OS", "The central core of the operating system that manages hardware", "An application for word processing", "A type of virus"],
    "answer": 1
  },
  {
    "question": "Which of the following is the smallest unit of data in a file system?",
    "options": ["Bit", "Byte", "Sector", "Cluster"],
    "answer": 1
  },
  {
    "question": "\"FAT\" stands for:",
    "options": ["File Access Table", "File Allocation Table", "Final Allocation Tool", "Format Address Table"],
    "answer": 1
  },
  {
    "question": "Which file system is native to modern Windows versions?",
    "options": ["FAT32", "EXT4", "NTFS", "HFS+"],
    "answer": 2
  },
  {
    "question": "The mechanism used to bring data into main memory only when it is actually needed is:",
    "options": ["Pre-paging", "Demand Paging", "Segmentation", "Buffering"],
    "answer": 1
  },
  {
    "question": "Which disk scheduling algorithm services requests in the exact order they arrive?",
    "options": ["SSTF", "SCAN", "FCFS (First-Come, First-Served)", "LOOK"],
    "answer": 2
  },
  {
    "question": "\"Spooling\" (Simultaneous Peripheral Operations On-Line) is primarily used to:",
    "options": ["Encrypt files", "Manage I/O jobs for slow devices like printers", "Speed up the internet", "Clean the hard drive"],
    "answer": 1
  },
  {
    "question": "In Linux, the \"root\" directory is represented by which symbol?",
    "options": ["\\", "/", "~", "$"],
    "answer": 1
  },
  {
    "question": "Which command is used to change file permissions in Linux?",
    "options": ["ls", "cd", "chmod", "chown"],
    "answer": 2
  },
  {
    "question": "What is a \"Ghost\" or \"Image\" of a hard drive?",
    "options": ["A deleted file", "A sector-by-sector copy of the drive", "A desktop shortcut", "A virus scan report"],
    "answer": 1
  },
  {
    "question": "Which of the following is NOT a necessary condition for a deadlock to occur?",
    "options": ["Mutual Exclusion", "Hold and Wait", "Preemption", "Circular Wait"],
    "answer": 2
  },
  {
    "question": "The \"Banker's Algorithm\" is primarily used for:",
    "options": ["Deadlock detection", "Deadlock avoidance", "Memory allocation", "Calculating interest rates"],
    "answer": 1
  },
  {
    "question": "A \"Mutex\" (Mutual Exclusion object) is used for:",
    "options": ["Faster internet", "Process Synchronization", "Deleting files", "Connecting to a database"],
    "answer": 1
  },
  {
    "question": "What is a \"Semaphore\"?",
    "options": ["A type of hardware cable", "An integer variable used for signaling between processes", "A graphical icon", "A partition on a hard drive"],
    "answer": 1
  },
  {
    "question": "The \"Critical Section\" is a part of a program where:",
    "options": ["The program terminates", "Shared resources (like variables or files) are accessed", "User input is requested", "Error messages are displayed"],
    "answer": 1
  },
  {
    "question": "Which of the following is an example of an \"Open Source\" Operating System?",
    "options": ["Windows 10", "macOS", "Ubuntu Linux", "iOS"],
    "answer": 2
  },
  {
    "question": "A \"Thread\" is also commonly known as a:",
    "options": ["Heavyweight Process", "Lightweight Process", "Program script", "Background service"],
    "answer": 1
  },
  {
    "question": "What is the purpose of \"Device Drivers\"?",
    "options": ["To play games", "To allow the OS to communicate with specific hardware", "To increase battery life", "To write code"],
    "answer": 1
  },
  {
    "question": "Which of the following is a GUI-based (Graphical User Interface) OS?",
    "options": ["MS-DOS", "Unix (Command Line)", "Windows 10", "CP/M"],
    "answer": 2
  },
  {
    "question": "\"Safe Mode\" in Windows is primarily used for:",
    "options": ["Faster gaming", "Troubleshooting and driver repair", "Watching movies", "Online shopping"],
    "answer": 1
  },
  {
    "question": "The command ipconfig in Windows is used to:",
    "options": ["Format the drive", "View network configuration (IP address, mask, etc.)", "Change the computer name", "Shutdown the PC"],
    "answer": 1
  },
  {
    "question": "What does \"SSTF\" stand for in disk scheduling?",
    "options": ["Standard System Task File", "Shortest Seek Time First", "Small Sector Transfer Format", "System Speed Task Force"],
    "answer": 1
  },
  {
    "question": "Which OS layer interacts directly with the computer hardware?",
    "options": ["Application layer", "Shell", "Kernel", "User interface"],
    "answer": 2
  },
  {
    "question": "The \"Blue Screen of Death\" (BSOD) is an error screen typical for which OS?",
    "options": ["Linux", "macOS", "Windows", "Android"],
    "answer": 2
  },
  {
    "question": "What is \"Fork\" in an operating system?",
    "options": ["Deleting a process", "The creation of a new process (child process)", "A type of network connector", "Closing a window"],
    "answer": 1
  },
  {
    "question": "Which of the following is a \"Real-Time Operating System\" (RTOS)?",
    "options": ["Windows 7", "RTLinux/QNX", "Ubuntu", "MS-DOS"],
    "answer": 1
  },
  {
    "question": "The \"Registry\" is a database used by which OS to store configuration settings?",
    "options": ["Linux", "Windows", "macOS", "Unix"],
    "answer": 1
  },
  {
    "question": "In Linux, the command grep is used to:",
    "options": ["Copy files", "Search for patterns (text) within files", "Move to a different directory", "List all users"],
    "answer": 1
  },
  {
    "question": "\"Time Quantum\" is a term specifically related to which scheduling algorithm?",
    "options": ["SJF", "FCFS", "Round Robin", "Priority"],
    "answer": 2
  },
  {
    "question": "The main advantage(s) of a \"Multiprocessor System\" include:",
    "options": ["Increased reliability", "Increased throughput", "Economy of Scale", "All of the above"],
    "answer": 3
  }
]
};